In [1]:
import numpy as np

In [2]:
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("iris.csv")

In [4]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [8]:
X_test = scaler.transform(X_test)

In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [11]:
lda = LinearDiscriminantAnalysis(n_components = 1)

In [12]:
X_train_lda = lda.fit_transform(X_train, y_train)

In [13]:
X_test_lda = lda.transform(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
classifier = RandomForestClassifier(max_depth = 2, random_state = 0)

In [16]:
classifier.fit(X_train_lda,y_train)
y_pred = classifier.predict(X_test_lda)

In [17]:
conf_matrix = confusion_matrix(y_test,y_pred)

In [18]:
accuracy = accuracy_score(y_test,y_pred)

In [19]:
print("Confusion_matrix:\n",conf_matrix)

Confusion_matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [20]:
print("Accuracy:",accuracy)

Accuracy: 1.0
