# Welcome to Numpy Tutorial

In [1]:
import numpy as np
#np works as an alias for numpy

In [2]:
myarr = np.array([[3,4,5,6]] , np.int8) 
#here datatype in the np.array is integer

In [3]:
myarr

array([[3, 4, 5, 6]], dtype=int8)

In [4]:
myarr[0,1]

4

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr

array([[3, 4, 5, 6]], dtype=int8)

In [8]:
myarr[0,2] = 69

In [9]:
myarr

array([[ 3,  4, 69,  6]], dtype=int8)

In [10]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
arr2.shape

(3, 3)

In [12]:
sum = 0
for i in range(3):
    sum+=arr2[i,i]
print(sum)

15


In [13]:
arr2.size

9

In [14]:
np.array({1,2,3,5})

array({1, 2, 3, 5}, dtype=object)

In [15]:
zeroes = np.zeros((2,5))

In [16]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
x = np.array([1,2,3])

In [18]:
x

array([1, 2, 3])

In [19]:
x = np.empty((3,3), dtype = complex)
print(x)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [20]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [21]:
y = np.ones(6) #6 means columns
print(y)

[1. 1. 1. 1. 1. 1.]


In [22]:
y = np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
z = np.ones((3,5), dtype = int)
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [24]:
z1 = np.zeros((3,5), dtype = float)
print(z1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
z1_1 = np.zeros((3,5), dtype = str)
print(z1_1)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [26]:
z2 = np.ones((3,4), dtype = str)
print(z2)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [27]:
z3 = np.ones((3,4), dtype = bool)
print(z3)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**np.arange(start, end, step)** #step not necessary as default step is 1

In [28]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
a = np.arange(1,20,2)

In [30]:
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [31]:
a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


**arr.reshape((rows,cols))**

In [32]:
a = a.reshape((3,3))
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**arr.flatten()** 
'''will convert a multidimensional array to 1D array'''

In [33]:
a = a.flatten()

In [34]:
print(a)

[ 2  4  6  8 10 12 14 16 18]


**arr.ravel()** <br>
i) Return only reference/view of original array <br>
ii) If you modify the array you would notice that the value of original array also changes. <br>
iii) Ravel is faster than flatten() as it does not occupy any memory. <br>
iv) Ravel is a library -level function. <br>

**arr.flatten()** <br>
i) Return copy of original array <br>
ii) If you modify the array the original array is not affected. <br>
iii) Flatten is slower than ravel as it occupies memory. <br>
iv) Flatten is a method of ndarray object. <br>

# NUMPY Slicing

In [35]:
a = np.arange(1,51)
a = a.reshape(10,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [36]:
a[0]

array([1, 2, 3, 4, 5])

In [37]:
a[2]

array([11, 12, 13, 14, 15])

In [38]:
a[0][0]

1

In [39]:
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [41]:
a[2:4,2:4]

array([[13, 14],
       [18, 19]])

# Mathematical operations

In [42]:
a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))
print(a)
print()
print(b)

[[9 1 6]
 [3 5 3]
 [7 5 1]]

[[9 5 3]
 [1 7 6]
 [8 9 2]]


In [43]:
a+b

array([[18,  6,  9],
       [ 4, 12,  9],
       [15, 14,  3]])

In [44]:
c = a+b
print(c)

[[18  6  9]
 [ 4 12  9]
 [15 14  3]]


In [45]:
np.add(a,b)

array([[18,  6,  9],
       [ 4, 12,  9],
       [15, 14,  3]])

In [46]:
# a+b = np.add(a,b)
# a-b = np.subtract(a,b)

In [47]:
a-b

array([[ 0, -4,  3],
       [ 2, -2, -3],
       [-1, -4, -1]])

In [48]:
#multiplication
np.multiply(a,b)

array([[81,  5, 18],
       [ 3, 35, 18],
       [56, 45,  2]])

In [49]:
#matrix multiplication

#method 1
res1 = a@b
print("res1\n",res1)
print()

#method 2
res2 = a.dot(b)
print("res2\n", res2)
print()

#method 3
res3 = np.dot(a,b)
print("res3\n", res3)
print()


res1
 [[130 106  45]
 [ 56  77  45]
 [ 76  79  53]]

res2
 [[130 106  45]
 [ 56  77  45]
 [ 76  79  53]]

res3
 [[130 106  45]
 [ 56  77  45]
 [ 76  79  53]]



# Printing Max element of a matrix row wise

In [50]:
print(a)
print()
for i in range(4):
    print(a[i,:])
    print(np.max(a[i,:]))

[[9 1 6]
 [3 5 3]
 [7 5 1]]

[9 1 6]
9
[3 5 3]
5
[7 5 1]
7


IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
print(a)
print()
for i in range(4):
    print(a[:,i])
    print(np.max(a[:, i]))

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
b.argmax() #it will return the index at which the maximum value is present

In [ ]:
np.sum(b)

In [ ]:
np.sum(b, axis = 1) # axis = 1 -> row, axis = 0 -> columns)

In [ ]:
np.mean(b) 

In [ ]:
np.sqrt(b) # return the square root of each element

In [ ]:
np.std(b) #return the standard deviation of all the elements of b

In [ ]:
np.log(a) #return the log of each element

# Trigonometric Functions

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
np.pi

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.sin(np.pi/6)

In [ ]:
np.cos(np.pi/2)   

In [ ]:
np.tan(np.pi/2)  #Huge value

In [ ]:
np.tan(0)

**Basic Matplotlib function**

In [ ]:
x = np.arange(1,11)
y = np.arange(10,110,10)

plt.figure(figsize = (6,6))
plt.plot(x,y, 'r--')
plt.show()

**Trigonometric Functions using matplotlib**

In [ ]:
x_sin = np.arange(0,2*np.pi,0.1)
y_sin = np.sin(x_sin)
print(y_sin)

In [ ]:
plt.figure(figsize = (6,6))
plt.plot(x_sin, y_sin)
plt.title("Sin Curve")
plt.show()

In [ ]:
x_cos = np.arange(0,2*np.pi,0.1)
y_cos = np.cos(x_cos)
print(y_cos)
plt.figure(figsize = (6,6))
plt.plot(x_cos, y_cos)
plt.title("Cos Curve")
plt.show()

In [ ]:
x_tan = np.arange(0,2*np.pi,0.1)
y_tan = np.tan(x_tan)
print(y_tan)
plt.figure(figsize = (6,6))
plt.plot(x_tan, y_tan)
plt.title("Tan Curve")
plt.show()

In [ ]:
x_cot = np.arange(0,2*np.pi,0.1)
y_cot = 1/np.tan(x_cot)

plt.figure(figsize = (6,6))
plt.plot(x_cot, y_cot)
plt.title("Cot Curve")
plt.show()

**Subplot**

In [ ]:
plt.figure(figsize = (8,8))
plt.subplot(2,2,1)
plt.plot(x_sin, y_sin, 'r--')
plt.title("Sin curve")

plt.subplot(2,2,2)
plt.plot(x_cos, y_cos)
plt.title("Cos curve")

plt.subplot(2,2,3)
plt.plot(x_tan, y_tan)
plt.title("Tan curve")

plt.subplot(2,2,4)
plt.plot(x_cot, y_cot)
plt.title("Cot curve")

plt.show()

# Random Operations

In [ ]:
np.random.random(1)

In [ ]:
np.random.random(2)

In [ ]:
np.random.random((2,2))

In [ ]:
np.random.randint(1,10)

In [ ]:
np.random.randint(1,10, (2,2))

In [ ]:
np.random.randint(1,10,(3,4,5))

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randn(2,2)

In [ ]:
a = np.arange(1,10)
print(a)

In [ ]:
np.random.choice(a)

  # String Operations

In [ ]:
s1 = "Abhra"
s2 = "neel"

In [ ]:
np.char.add(s1,s2)

In [ ]:
np.char.upper(s1)

In [ ]:
np.char.lower(s1)

In [ ]:
np.char.split(s1)

In [ ]:
np.char.replace(s1, '','#')

In [ ]:
print(np.char.center('A', 8,'*'))

In [ ]:
import pandas as pd